BEGIN;
CREATE TABLE IF NOT EXISTS public.levelup_roles(user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN ('STUDENT','ADMIN','REVIEWER')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.exams(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL,name text NOT NULL,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED')),sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.exam_sections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),exam_id uuid NOT NULL REFERENCES public.exams(id),code text NOT NULL,name text NOT NULL,description text NOT NULL DEFAULT '',sort_order integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(exam_id,code));
CREATE TABLE IF NOT EXISTS public.domains(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL,name text NOT NULL,description text NOT NULL DEFAULT '',sort_order integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.topics(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),domain_id uuid NOT NULL REFERENCES public.domains(id),code text UNIQUE NOT NULL,slug text UNIQUE NOT NULL,name text NOT NULL,description text NOT NULL DEFAULT '',sort_order integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.subtopics(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),topic_id uuid NOT NULL REFERENCES public.topics(id),code text UNIQUE NOT NULL,slug text UNIQUE NOT NULL,name text NOT NULL,description text NOT NULL DEFAULT '',sort_order integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.content_sources(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_type text NOT NULL CHECK(source_type IN ('ORIGINAL','PAST_EXAM','ADAPTED','PDF','EXCEL','AI_ASSISTED','OTHER')),title text NOT NULL,author_or_publisher text,year integer,file_name text,source_url text,notes text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.questions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL CHECK(code ~ '^[A-Z0-9][A-Z0-9-]{0,79}$'),current_version_id uuid,status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED','TEST_ONLY')),source_type text NOT NULL DEFAULT 'ORIGINAL' CHECK(source_type IN ('ORIGINAL','PAST_EXAM','ADAPTED','PDF','EXCEL','AI_ASSISTED','OTHER')),created_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.question_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),question_id uuid NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,version_number integer NOT NULL CHECK(version_number>0),question_type text NOT NULL DEFAULT 'SINGLE_CHOICE' CHECK(question_type='SINGLE_CHOICE'),section_id uuid NOT NULL REFERENCES public.exam_sections(id),subtopic_id uuid NOT NULL REFERENCES public.subtopics(id),difficulty text NOT NULL CHECK(difficulty IN ('BASIC','MEDIUM','HARD')),instruction_md text,stimulus_md text,stem_md text NOT NULL DEFAULT '',primary_skill text,status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','IN_REVIEW','QA_PASSED','PUBLISHED','ARCHIVED')),source_id uuid REFERENCES public.content_sources(id),source_page text,created_by uuid NOT NULL REFERENCES auth.users(id),updated_by uuid REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz,UNIQUE(question_id,version_number));
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='questions_current_version_fk') THEN ALTER TABLE public.questions ADD CONSTRAINT questions_current_version_fk FOREIGN KEY(current_version_id) REFERENCES public.question_versions(id) DEFERRABLE INITIALLY DEFERRED; END IF; END $$;
CREATE TABLE IF NOT EXISTS public.question_options(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),question_version_id uuid NOT NULL REFERENCES public.question_versions(id) ON DELETE CASCADE,option_key text NOT NULL CHECK(option_key IN ('A','B','C','D','E')),content_md text NOT NULL,sort_order integer NOT NULL,is_correct boolean NOT NULL DEFAULT false,UNIQUE(question_version_id,option_key),UNIQUE(question_version_id,sort_order));
CREATE TABLE IF NOT EXISTS public.question_explanations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),question_version_id uuid UNIQUE NOT NULL REFERENCES public.question_versions(id) ON DELETE CASCADE,understanding_md text NOT NULL DEFAULT '',known_md text,asked_md text,concept_md text NOT NULL DEFAULT '',first_step_md text NOT NULL DEFAULT '',solution_md text NOT NULL DEFAULT '',final_answer_md text NOT NULL DEFAULT '',shortcut_md text,common_mistake_md text,option_analysis_md text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.media_assets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),kind text NOT NULL CHECK(kind IN ('IMAGE','DIAGRAM','DOCUMENT')),original_filename text NOT NULL,storage_provider text NOT NULL CHECK(storage_provider='SUPABASE'),storage_path text NOT NULL CHECK(storage_path<>'' AND storage_path NOT LIKE '%..%' AND storage_path NOT LIKE '%://%' AND storage_path NOT LIKE '/%'),mime_type text NOT NULL,width integer CHECK(width>0),height integer CHECK(height>0),file_size bigint NOT NULL CHECK(file_size>=0),alt_text text,source_url text,created_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.question_media(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),question_version_id uuid NOT NULL REFERENCES public.question_versions(id) ON DELETE CASCADE,media_asset_id uuid NOT NULL REFERENCES public.media_assets(id),role text NOT NULL CHECK(role IN ('STIMULUS','QUESTION','OPTION','EXPLANATION')),sort_order integer NOT NULL DEFAULT 0,UNIQUE(question_version_id,media_asset_id,role));
CREATE TABLE IF NOT EXISTS public.learning_modules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),subtopic_id uuid NOT NULL REFERENCES public.subtopics(id),code text UNIQUE NOT NULL,slug text UNIQUE NOT NULL,title text NOT NULL,description text NOT NULL DEFAULT '',level text NOT NULL CHECK(level IN ('FOUNDATION','STANDARD','ADVANCED')),status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','IN_REVIEW','QA_PASSED','PUBLISHED','ARCHIVED')),sort_order integer NOT NULL DEFAULT 0,estimated_minutes integer NOT NULL CHECK(estimated_minutes>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz);
CREATE TABLE IF NOT EXISTS public.learning_lessons(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),module_id uuid NOT NULL REFERENCES public.learning_modules(id) ON DELETE CASCADE,title text NOT NULL,slug text NOT NULL,description text,sort_order integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','IN_REVIEW','QA_PASSED','PUBLISHED','ARCHIVED')),estimated_minutes integer NOT NULL CHECK(estimated_minutes>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(module_id,slug));
CREATE TABLE IF NOT EXISTS public.lesson_blocks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid NOT NULL REFERENCES public.learning_lessons(id) ON DELETE CASCADE,block_type text NOT NULL CHECK(block_type IN ('HEADING','TEXT','LATEX','IMAGE','CALLOUT','EXAMPLE','COMMON_MISTAKE','SUMMARY')),sort_order integer NOT NULL DEFAULT 0,content_json jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.lesson_question_assignments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),lesson_id uuid NOT NULL REFERENCES public.learning_lessons(id) ON DELETE CASCADE,question_version_id uuid NOT NULL REFERENCES public.question_versions(id),role text NOT NULL CHECK(role IN ('CHECKPOINT','GUIDED','MINI_ASSESSMENT','REINFORCEMENT')),sort_order integer NOT NULL DEFAULT 0,UNIQUE(lesson_id,question_version_id,role));
CREATE TABLE IF NOT EXISTS public.content_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),entity_type text NOT NULL CHECK(entity_type IN ('QUESTION_VERSION','LEARNING_MODULE','LESSON','ASSESSMENT_REVISION')),entity_id uuid NOT NULL,review_type text NOT NULL CHECK(review_type IN ('MATH','EDITORIAL','PACKAGE')),status text NOT NULL CHECK(status IN ('APPROVED','REJECTED','CHANGES_REQUESTED')),reviewer_id uuid NOT NULL REFERENCES auth.users(id),notes text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.import_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_type text NOT NULL DEFAULT 'EXCEL',file_name text NOT NULL,status text NOT NULL CHECK(status IN ('UPLOADED','PARSING','VALIDATION_FAILED','READY_FOR_REVIEW','IMPORTED','FAILED')),created_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,summary_json jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS public.import_rows(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),import_job_id uuid NOT NULL REFERENCES public.import_jobs(id) ON DELETE CASCADE,row_number integer NOT NULL,raw_json jsonb NOT NULL,parsed_json jsonb,status text NOT NULL CHECK(status IN ('VALID','INVALID','SKIPPED','IMPORTED')),error_message text,question_id uuid REFERENCES public.questions(id),UNIQUE(import_job_id,row_number));
CREATE OR REPLACE FUNCTION public.levelup_current_version_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN IF NEW.current_version_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.question_versions WHERE id=NEW.current_version_id AND question_id=NEW.id) THEN RAISE EXCEPTION 'current version must belong to question';END IF;RETURN NEW;END $$;
DROP TRIGGER IF EXISTS current_version_owner ON public.questions;
CREATE TRIGGER current_version_owner BEFORE INSERT OR UPDATE OF current_version_id ON public.questions FOR EACH ROW EXECUTE FUNCTION public.levelup_current_version_guard();
REVOKE ALL ON FUNCTION public.levelup_current_version_guard() FROM PUBLIC,anon,authenticated;
CREATE INDEX IF NOT EXISTS question_versions_classification_idx ON public.question_versions(section_id,subtopic_id,difficulty,status);
CREATE INDEX IF NOT EXISTS question_versions_question_idx ON public.question_versions(question_id,version_number DESC);
CREATE INDEX IF NOT EXISTS content_reviews_entity_idx ON public.content_reviews(entity_type,entity_id,created_at DESC);

CREATE OR REPLACE FUNCTION public.levelup_content_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
DECLARE vid uuid;
BEGIN
 IF TG_TABLE_NAME='question_versions' THEN
  IF OLD.status='PUBLISHED' THEN RAISE EXCEPTION 'published version immutable'; END IF;
 ELSE
  IF TG_OP='UPDATE' AND NEW.question_version_id<>OLD.question_version_id THEN RAISE EXCEPTION 'version relationship immutable'; END IF;
  vid:=CASE WHEN TG_OP='INSERT' THEN NEW.question_version_id ELSE OLD.question_version_id END;
  IF EXISTS(SELECT 1 FROM public.question_versions WHERE id=vid AND status='PUBLISHED') THEN RAISE EXCEPTION 'published version immutable'; END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END $$;
DROP TRIGGER IF EXISTS immutable_version ON public.question_versions;
CREATE TRIGGER immutable_version BEFORE UPDATE OR DELETE ON public.question_versions FOR EACH ROW EXECUTE FUNCTION public.levelup_content_immutable();
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['question_options','question_explanations','question_media'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS immutable_content ON public.%I',t);EXECUTE format('CREATE TRIGGER immutable_content BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.levelup_content_immutable()',t); END LOOP;END $$;
CREATE OR REPLACE FUNCTION public.levelup_question_ready(vid uuid) RETURNS boolean LANGUAGE sql STABLE SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.question_versions v JOIN public.exam_sections s ON s.id=v.section_id JOIN public.exams x ON x.id=s.exam_id JOIN public.subtopics st ON st.id=v.subtopic_id JOIN public.topics t ON t.id=st.topic_id JOIN public.domains d ON d.id=t.domain_id JOIN public.question_explanations e ON e.question_version_id=v.id WHERE v.id=vid AND length(trim(v.stem_md))>0 AND s.status='ACTIVE' AND x.status='ACTIVE' AND st.status='ACTIVE' AND t.status='ACTIVE' AND d.status='ACTIVE' AND length(trim(e.understanding_md))>0 AND length(trim(e.concept_md))>0 AND length(trim(e.first_step_md))>0 AND length(trim(e.solution_md))>0 AND length(trim(e.final_answer_md))>0) AND (SELECT count(*) BETWEEN 4 AND 5 AND count(*) FILTER(WHERE is_correct)=1 AND count(DISTINCT lower(trim(content_md)))=count(*) AND bool_and(length(trim(content_md))>0) FROM public.question_options WHERE question_version_id=vid);
$$;
CREATE OR REPLACE FUNCTION public.levelup_publish_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
BEGIN
 IF TG_OP='INSERT' THEN IF NEW.status<>'DRAFT' THEN RAISE EXCEPTION 'new version must be draft'; END IF;RETURN NEW;END IF;
 IF NEW.status IN ('IN_REVIEW','QA_PASSED','PUBLISHED') AND NOT public.levelup_question_ready(NEW.id) THEN RAISE EXCEPTION 'question incomplete or invalid answer/classification'; END IF;
 IF NEW.status='PUBLISHED' AND (OLD.status<>'QA_PASSED' OR NOT EXISTS(SELECT 1 FROM public.content_reviews WHERE entity_type='QUESTION_VERSION' AND entity_id=NEW.id AND status='APPROVED')) THEN RAISE EXCEPTION 'QA approval required before publication'; END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS publication_guard ON public.question_versions;
CREATE TRIGGER publication_guard BEFORE INSERT OR UPDATE OF status ON public.question_versions FOR EACH ROW EXECUTE FUNCTION public.levelup_publish_guard();
CREATE OR REPLACE FUNCTION public.levelup_option_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
DECLARE vid uuid:=CASE WHEN TG_OP='DELETE' THEN OLD.question_version_id ELSE NEW.question_version_id END;
BEGIN
 IF (SELECT count(*) FROM public.question_options WHERE question_version_id=vid AND is_correct)>1 THEN RAISE EXCEPTION 'exactly one correct answer'; END IF;
 IF EXISTS(SELECT 1 FROM public.question_versions WHERE id=vid AND status IN ('IN_REVIEW','QA_PASSED','PUBLISHED')) AND NOT public.levelup_question_ready(vid) THEN RAISE EXCEPTION 'question incomplete or invalid answer'; END IF;
 RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS one_correct_option ON public.question_options;
CREATE CONSTRAINT TRIGGER one_correct_option AFTER INSERT OR UPDATE OR DELETE ON public.question_options DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.levelup_option_guard();
CREATE OR REPLACE FUNCTION public.levelup_question_delete_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN IF EXISTS(SELECT 1 FROM public.question_versions WHERE question_id=OLD.id AND status='PUBLISHED') THEN RAISE EXCEPTION 'published question cannot be deleted'; END IF;RETURN OLD;END $$;
DROP TRIGGER IF EXISTS protect_published_question ON public.questions;
CREATE TRIGGER protect_published_question BEFORE DELETE ON public.questions FOR EACH ROW EXECUTE FUNCTION public.levelup_question_delete_guard();

CREATE OR REPLACE VIEW public.levelup_question_bank AS
 SELECT q.id,q.code,q.current_version_id,q.status logical_status,q.source_type,q.updated_at,v.id version_id,v.version_number,CASE WHEN q.status='ARCHIVED' THEN 'ARCHIVED' ELSE v.status END status,v.stem_md,v.difficulty,v.section_id,v.subtopic_id,s.code section,s.exam_id,x.code exam,st.topic_id,st.name subtopic,t.domain_id,t.name topic,d.name domain,cs.title source_title
 FROM public.questions q JOIN LATERAL(SELECT * FROM public.question_versions WHERE question_id=q.id ORDER BY version_number DESC LIMIT 1) v ON true JOIN public.exam_sections s ON s.id=v.section_id JOIN public.exams x ON x.id=s.exam_id JOIN public.subtopics st ON st.id=v.subtopic_id JOIN public.topics t ON t.id=st.topic_id JOIN public.domains d ON d.id=t.domain_id LEFT JOIN public.content_sources cs ON cs.id=v.source_id;

-- Minimal taxonomy only, never teaching/question seed content.
INSERT INTO public.exams(id,code,name) VALUES('10000000-0000-4000-8000-000000000001','SNBT','Seleksi Nasional Berdasarkan Tes') ON CONFLICT(code) DO NOTHING;
INSERT INTO public.exam_sections(id,exam_id,code,name,sort_order) VALUES
 ('11000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','PK','Pengetahuan Kuantitatif',1),
 ('11000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001','PM','Penalaran Matematika',2),
 ('11000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000001','PU','Penalaran Umum',3) ON CONFLICT(exam_id,code) DO NOTHING;
INSERT INTO public.domains(id,code,name) VALUES('12000000-0000-4000-8000-000000000001','ARI','Bilangan dan Aritmetika'),('12000000-0000-4000-8000-000000000002','ALG','Aljabar') ON CONFLICT(code) DO NOTHING;
INSERT INTO public.topics(id,domain_id,code,slug,name) VALUES('13000000-0000-4000-8000-000000000001','12000000-0000-4000-8000-000000000001','NUM','bilangan','Bilangan'),('13000000-0000-4000-8000-000000000002','12000000-0000-4000-8000-000000000002','LIN','linear','Persamaan Linear') ON CONFLICT(code) DO NOTHING;
INSERT INTO public.subtopics(id,topic_id,code,slug,name) VALUES('14000000-0000-4000-8000-000000000001','13000000-0000-4000-8000-000000000001','RATIO','rasio','Rasio dan Perbandingan'),('14000000-0000-4000-8000-000000000002','13000000-0000-4000-8000-000000000002','EQ','persamaan-linear','Persamaan Linear Satu Variabel'),('14000000-0000-4000-8000-000000000003','13000000-0000-4000-8000-000000000001','PERCENT','persen','Persentase') ON CONFLICT(code) DO NOTHING;

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['levelup_roles','exams','exam_sections','domains','topics','subtopics','content_sources','questions','question_versions','question_options','question_explanations','media_assets','question_media','learning_modules','learning_lessons','lesson_blocks','lesson_question_assignments','content_reviews','import_jobs','import_rows'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated',t);EXECUTE format('GRANT ALL ON public.%I TO service_role',t);END LOOP;END $$;
REVOKE ALL ON public.levelup_question_bank FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.levelup_question_bank TO service_role;
REVOKE ALL ON FUNCTION public.levelup_question_ready(uuid),public.levelup_content_immutable(),public.levelup_publish_guard(),public.levelup_option_guard(),public.levelup_question_delete_guard() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.levelup_question_ready(uuid) TO service_role;
COMMIT;
